### ISSUE TITLE
Migration to 12.0

### ISSUE THREAD

**Issue by remytms** [beescoop/Obeesdoo#129]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0

Branch 12.0 has been released !

Guide lines: https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst

# Modules to migrate

:beginner: : This tag means that migrating can be taken by a beginner. :)
A checked box ([x]) indicates that the PR has already been merged.

* [x] beesdoo_account - @aborsu - #109
* [x] beesdoo_base
* [x] :beginner: beesdoo_custom @StCyr #135 
* [ ] :beginner: beesdoo_easy_my_coop @StCyr #134 (WIP)
* [x] beesdoo_pos
* [x] beesdoo_pos_remove_0_qty @houssine78 - https://github.com/coopiteasy/pos/tree/12.0-mig-pos_remove_0_qty
* [x] beesdoo_product
* [x] beesdoo_purchase - @sdegueldre - #114
* [x] beesdoo_inventory - @sdegueldre - #111
* [x] beesdoo_shift - @elouan-lb - #133
* [x] :beginner: beesdoo_stock @vvrossem - #144 
* [x] beesdoo_stock_coverage (stock_coverage) @robinkeunen #139 
* [x] :beginner: beesdoo_website_eater (check also beesdoo_website_posorder_amount) @StCyr #132
* [ ] beesdoo_website_portal - Merge it with beesdoo_custom
* [x] :beginner: beesdoo_website_posorder_amount - @StCyr #131 
* [x] beesdoo_website_theme - @NadTr - #113
* [x] beesdoo_website_shift - @remytms - #133
* [ ] compute_purchase_order: do we still have performance problems in 12.0?

# Not sure
* beesdoo_crelan_csv (is it already existing in OCA ?)
* [ ] beesdoo_purchase_manual_date_planned - Need to be validate in 9.0 first

# Do not migrate
* beesdoo_report (not used)
* partner_firstname (see with @robinkeunen)
* beesdoo_coda
* admin_technical_features
* base_technical_features
* mass_editing
* pos_access_right - It's an OCA module
* pos_price_to_weight - Will use the OCA one.
* web_environment_ribbon - It's an OCA module already migrated
* beesdoo_project - Not used anymore
* pos_keyboard - It's an OCA module already migrated

**Comment by houssine78** [comment]
@remytms can you add the modules of this repo to the migration process ? beesdoo_custom depends on at least one of those module. https://github.com/coopiteasy/procurement-addons

**Comment by robinkeunen** [comment]
Yo,
Je rajouter les modules de procurement-addons. Je les rappatrierai dans ce repo-ci. 

(mes premiers modules odoo, àa va piquer les yeux <3)

**Comment by mclaeysb** [comment]
Let's not forget that `beesdoo_pos` has not been migrated completely yet!

**Comment by remytms** [comment]
Branch 12.0 has been released !

**Comment by remytms** [comment]
Thanks all for the huge work ! :)

**Comment by robinkeunen** [comment]
🎉Fais-toi plaisir: branche par défaut! 🎉

**Comment by StCyr** [comment]
y a plus rien à faire du coup?
